### ISSUE TITLE
DDJ-SB Audio

### ISSUE THREAD

**Issue by Ojggaspar** [wingcom/Mixxx-Pioneer-DDJ-SB#3]
Hi! Sorry, this may not be directly about this, but I didn´t know how to reach you other way...
I just would like to know if you managed to get your DDJ-SB to process sound output in linux?

I know its MIDI capabilities work, but I could not use the internal USB Soundcard from the DDJSB, 
have you?

Sorry if this not an appropriate topic here...
Thank you

**Comment by wingcom** [comment]
Do you mean that in Mixxx, under Preferences > Sound Hardware > Output (tab) you can not set the Master (channel 1-2) or the Headphone (channel 3-4) to your PIONEER-DDJ-SB?

This has always worked with me... it was not set by default though. I needed to manually change this at first start. If this is not set correctly - it will point to your internal soundcard - you will need to do stuff like change volum in the software on your pc. If this is set correctly, you can control the volume with your controller.

Otherwise I'm afraid I can't help you...

**Comment by Ojggaspar** [comment]
Hi, the pioneer DDJ-SB works correctly in windows, but I'm talking about
linux, I cannot use the internal soundcard of the DDJ-SB in Linux, thats
why I'm asking if you have managed to do it in Linux with Mixxx. Yes, I've
done that of setting the hardware options under Mixxx preferences under
Linux but nothing! What I really would like to know is if you managed to
get your DDJSB to work as an USB audio soundcard in linux.

Thanks for your time : )
I'll wait your reply.
Best,
Otávio

2015-05-28 19:34 GMT+00:00 wingcom notifications@github.com:

**Comment by wingcom** [comment]
But your device "ddj-sb" is in the dropdown box? You can choose it in Mixxx?

But you hear nothing? I think I had that one too... I needed to set something in Alsa Mixer I think... not quite sure. (http://en.wikipedia.org/wiki/Alsamixer) There was a Volume control there all the way down, the line in i guess.

Try that ;)

Edit: It might just be your setup. How is everything connected? As you can see, in my case I rerouted the output back into the pc soundcard, that's why i needed line in to be "unmuted" in alsamixer. I did this because the SB has only one output and I wanted to connect my stereo AND monitor speakers.

**Comment by wingcom** [comment]
You have good timing for this problem, as I am trying to install a usb audio adapter at this moment and faced the same problems...

First thing you need to do is make sure your ddj-sb is recognized as a sound device by your kernel. In order for it to recognize it, "soundcore" needs to be loaded into the kernel. Test with "modprobe soundcore" to see if it's loaded. You can also test if the alsa soundsystem is seeing your device with "aplay -l". Your device should be listed there as well. If it's not, you need to recompile your kernel with an option to enable it. Most latest linux versions have it though.

After this you can use the tools pavucontrol (it's a pulseaudio configuration tool) so set your default devices, see if you can route normal audio to your device. You can start playing a sound with a program of choice, it will appear on the playback tab in pavucontrol where you can set on which card you want to play. Another configuration tool which let's you set the device order for playback as well as recording is Phonon (might be kde only, don't know)

And as I said: check all the settings in alsamixer to see the volume is turned on for everything. If you have sound in these configuration tools, you should be able to make your setup work in Mixxx too. Tell me how you connected everything and what your system configuration (os, kernel, are you using gnome or kde? etc...) is, I might be able to better help you that way.

yo

**Comment by Ojggaspar** [comment]
Hi there,

The soundcard as always been detected from beginning and correctly, with
modprobe or alsa aplay. I could always select it in Mixxx or any other
software that could select the áudio device. The problem, is the fact that
it simply does not reproduce sound, the softwares play (it is possible to
see the volume meters working and all) but no physical sound output can be
heard.

Another thing is that when I run alsamixer it shows no controllers for the
device, and it says the chip is: USB mixer. Knowing this I even bother to
install arch Linux (because of better oss support for this kind of
soundcard) but of no avail. Tried to compile a kernel and all that trouble,
tried Softvol plugin. Reverted to ubuntu again and nothing. Pavucontrol was
the same thing.

After all this I had to get back to Windows and everything works fine...
Drivers installed and moving on.

Its a bit disappointing, I´ve spent almost a week trying to get this to
work in Linux, went to forums and all that, even bother to buy an external
soundcard which worked, but still could not use ddjsb internal soundcard.

What made me really curious was the fact that you gave the impression you
had used DDJSB internal soundcard in Linux and it worked correctly, and
still I´m not sure if you had done it or not! Can you confirm me that you
made the internal soundcard of DDJ-SB work in Linux? In Mixxx or whatever
software in Linux? Please just answer this question : ) Yes or No? The MIDI
works perfectly, I´m talking about physical sound output in Linux from the
DDJSB.

Thank you very much for your time and atention, I really appreciate it.
Best,

OG

2015-06-01 7:39 GMT+01:00 wingcom notifications@github.com:

**Comment by wingcom** [comment]
First of all, to answer your question: YES, I output my sound to the DDJ-SB and sound is coming out of it. I actually have tried many setups, including disabling EVERY sound device on the system except for the ddj-sb and I still have sound (if i connect the ddj-sb output to speaker directly then since my soundcard is disabled, the line in which i normally use, is also disabled). So yes, it works like it's intended. 

It'll be something small that we are overlooking.

What I would try first is, in pavucontrol, disable all soundcards on the system except for the DDJ-SB. Just put everything in OFF mode and put the DDJ-SB to Analogue output. Then on the DDJ-SB, connect your speakers directly to the output. 

Ive noticed that in alsamixer too, those "this device does not have any controls"... I don't think you need to worry about it, I've read a post on the alsa wiki pages that some usb devices just don't have any controls. My focusrite scarlett 2i4 doesn't have any either, yet it works... same with the ddj-sb... no controls but it works.

Then make sure in alsamixer and in pavucontrol that nothing is muted (even if you think the setting won't make a difference, turn it up anyway)

Also with aplay -l check the number of your card and try to send audio through it directly:
alsaplayer -o alsa -d hw:0,0  tune.mp3

Before  trying stuff with Mixxx, I would try to get these basics to work first. If your usb-device is recognized and if it plays in Windows then this needs to be a setting, we just haven't found it yet.

**Comment by Ojggaspar** [comment]
Incredible,
I´ve bought the 2i4 too a few days ago.

Which Linux distro are you using? Maybe its that...

2015-06-01 11:45 GMT+01:00 wingcom notifications@github.com:

**Comment by wingcom** [comment]
hehe nice. 

I bought it because I had a zoom on my loudspeakers. My collegue, who's a dj, told me this was caused because of a ground loop, for which in most cases the PC is the source. I also wanted to output to my loudspeakers AND to my monitors while the DDJ-SB only has one output. The focusrite did not solve all my problems however. The sound is working when I set my sound output to the DDJ-SB, then input this into front input 1 of the focusrite and then output to both speaker sets (unbalanced) This gives me a mono sound only on my monitors - stereo works but I'm only hearing something on the left speaker -  but it won't play on the other speakersystem (the receiver) because that source is not controlled by the front inputs, it's only directed to these when you your playback source is the computer (the usb cable)

The zoom, is gone ... at least that's one thing. 

So not quite sure if I really needed this device actually. It will come in handy someday, I'm sure... but at this time I might have wasted some money on it :/

I'm running Ubuntu 12.04 LTS 

Currently I'm using an somewhat older kernel (2 releases behind... because in the new kernel my Raid Device stopped working)

Also, I did those updates to have support untill 2017 (some internal/kernel thing changed a while ago, I think it was systemd stuff or something) So while still on 12.04 LTS, I'm supported untill 2017...

**Comment by Ojggaspar** [comment]
Ok, maybe its the 12.04 LTS vs latest Ubuntu, they stopped supporting some
features and updated to others... I ´ll try 12.04 LTS in the future to test
with DDJSB, at the moment i ´ve to stick with Windows, which actually is
doing quite good to my surprise due to the laptop power fact...

Anyway i ´m really thankful for the support from you,
Really nice to meet you,
If you have a webpage or some artist/producer stuff please tell me.

Best regards,
OG

2015-06-01 13:00 GMT+01:00 wingcom notifications@github.com:

**Comment by wingcom** [comment]
Also very good for me... now I know I don't need to update and keep my trusted 12.04
I've been considering this. But especially for the raid controller, i've put it on hold.

Will be "on hold" a bit longer...

No problem m8, too bad I couldn't help you.
I don't really have a producer page or something, but thanks anyway :)

I've come to the conclusion that for dj'ing, Windows offers more abilities then Linux... also better if you want to integrate iTunes etc (i'm also mixing on my ipad, using the same libraries in different software comes in handy) And while my mapping works, it's by far not optimal... I should work a bit on Serato windows too, before I work on it further. This way I will have a better understanding of how everything SHOULD work.

Nice to meet you too, have fun dj'ing!

**Comment by wingcom** [comment]
Hey Ojggaspar, 

One more thing... I removed my Focusrite 2i4 device yesterday because I really don't need it, it does not do what I intended it for.

Anyways: after removing this one I had exactly the same problem as you did. My sound devices seemed to be configured correctly but I had no sound... nowhere.

I also noticed that in Phonon, my Focusrite device still shows up. I guess this is a bad cleanup from udev or something.

Anyways, I did a few things and now my sound is working again whenever I have started Mixxx. Sound is not working when I boot - as in: everything is set to the ddj-sb but system sounds are not being sent over the ddj-sb. When I have started Mixxx 1 time now, sound is back. I can live with that because that PC is only meant as a mediaserver and my dj-pc.

However: there was no sound in Mixxx or after starting Mixxx just after I removed the Focusrite device. So here are the steps I did to get it back:

I logged into kde as root and started Phonon. Phonon will ask to permanently remove unused devices. I clicked 'yes' (actually, this is why I did this because it asks me this question as normal user too but nothing happens, they are still there) Then I reordered my Phonon device list and put the DDJ-SB at the top in every possible configuration (music, recording etc) And I do mean: at the top, so no grayed-out devices are above it either.

I did the same thing for the normal user. All my devices, except for the ddj-sb are in "Off" mode in pavucontrol and Phonon and the DDJ-SB is at the top of the list

I also created a .asoundrc file but after some testing now, that doesn't seem to do much. I've removed it now. It was basicly setting the default device for usb to card 1 which is the ddj-sb.

I also removed the following files: 

~/.kde4/share/config/phonondevicesrc
and
/var/tmp/kdecache-username/libphonon/

Anyways: I'm back up and running now ... whenever I start Mixxx. Mixxx seems to "switch on" the soundcard of the ddj-sb. It's like it's in sleep mode untill I start Mixxx... This might be solved with some script somewhere but I don't really mind starting Mixxx to get sound to work.

Sources:

http://www.linuxquestions.org/questions/linux-hardware-18/kde-permenently-remove-sound-device-4175518155/

http://blog.ostermiller.org/ubuntu-usb-audio/ (did not try this since I only have one device left but seems interesting)

http://alsa.opensrc.org/MultipleCards

yo

**Comment by Ojggaspar** [comment]
Ok man!
Thanks : )

At the time I did not log in as root in KDE, only used sudo... maybe that´s
another point to ckeck. Almost feel stupid not to have done it...

Still I know to have moved DDJ-SB to the top and removed all other devices,
putting it as card 0 but nothing... It must be 12.04 LTS vs latest, I ´ve
read they also disabled OSS support from exactly that version (12-04), I
think... so there must be something about that OS version, or maybe not...

Anyway thank you again for the tips, next time I install Ubuntu it will
probably be that version with those tips : )

Using serato in Windows with Renoise and FL is working fine at the moment,
I ´m more focused on stability and productivity now... I need to move on if
I want to make a living with music, but I think I will never give up on
Linux for future production.

Yesterday tested the 2 inputs from 2i4, they work very good, its a good
board to experiment things with mics and instruments, and so portable.

Thank you again!
Best regards,
OG

2015-06-03 7:52 GMT+01:00 wingcom notifications@github.com:
